name: Release to Discord
on:
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    name: Release to Discord
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          color: "16021398" # decimal of #f47796
          username: "Mise à jour de OpenMC"
          avatar_url: "https://raw.githubusercontent.com/ServerOpenMC/.github/refs/heads/master/brandkit/logo.png"
          #content: "||<@&1258420105209974804>||"
          footer_title: "Changements"
          footer_icon_url: "https://raw.githubusercontent.com/ServerOpenMC/.github/refs/heads/master/brandkit/logo.png"
          footer_timestamp: true
          max_description: '16384'
          reduce_headings: true
